### PR TITLE
fix the order when number of cases exceeds 10

### PR DESCRIPTION
**Pull request by ntflc**
When number of cases exceeds 10, the order of cases goes wrong.
For example:

``` python
class MyTest(unittest.TestCase):
    @parameterized.expand([
        (1, 1, 2),
        (2, 2, 4),
        (3, 3, 6),
        (4, 4, 8),
        (5, 5, 10),
        (6, 6, 12),
        (7, 7, 14),
        (8, 8, 16),
        (9, 9, 18),
        (10, 10, 20),
        (11, 11, 22)
    ])
    def test_add(self, a, b, c):
        self.assertEqual(a + b, c)
```
The order is `(1, 1, 2) (2, 2, 4) (11, 11, 22) (3, 3, 6) (4, 4, 8) (5, 5, 10) (6, 6, 12) (7, 7, 14) (8, 8, 16) (9, 9, 18) (10, 10, 20)`, because testMethod is `test_add_0, test_add_1, test_add_10, test_add_2...`
I change the name of testMethod to `test_add_00, test_add_01, test_add_02...`, so the order corrects now.

### CODE REVIEW

**Comment by wolever** [comment]
Nice catch. For completeness, though, this should use something like `"{zeros:num}".format(zeros=ceil(log(num, 10)), num=num)` so it can handle numbers beyond 99 too. Make that fix, make sure there's a test case, and we'll be good to merge!

**Comment by ntflc** [comment]
@wolever thanks for replying.
the variable "digit" in `digit = len(str(len(paramters) - 1))` has considered numbers beyond 99.
`"{1:0>{0}}".format(digit, num)` may be confused so I changed it to `"{num:0>{digit}}".format(digit=digit, num=num)`
and I have added test case for both 11 cases and 101 cases

**Comment by wolever** [comment]
D'oh! Yes, you're right - I just can't read.

Please:
- Update the tests so only a handful (like, 5 or 6) are added; as gratifying as it is to see 160 dots, that is a bit misleading.
- Add a note to the Changelog

And I'll get this in the next release!

**Comment by ntflc** [comment]
@wolever I have deleted the case with 101 parameters (test_cases_over_101).
I keep the case (test_cases_over_10) for it can reflect this fix.

**Comment by wolever** [comment]
Woo! I totally forgot about merging this, but it's in now and a new release will be out today :)

**Comment by ntflc** [comment]
@wolever could you release a new version (maybe 0.6.2) in https://pypi.python.org/pypi/parameterized please?

**Pull request merged**
